name: Mimic automated tests

on:
  push:
    branches:
      - '*'

permissions:
  contents: read
  statuses: write

jobs:
  create_automated_test_check:
    runs-on: ubuntu-latest
    steps:
      - name: Set Automated tests status to pending
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'pending',
              context: 'Automated tests',
              description: 'Awaiting manual QA result'
            })

  update_automated_test_check_status:
    runs-on: ubuntu-latest
    needs: create_automated_test_check
    steps:
      - name: Set Automated tests status to randomly picked
        uses: actions/github-script@v7
        with:
          script: |
            const statuses = ['error', 'failure', 'pending', 'success'];
            const randomStatus = statuses[Math.floor(Math.random() * statuses.length)];
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: randomStatus,
              context: 'Automated tests',
              description: `Status randomly set to ${randomStatus}`
            })
      - name: Output result
        run: echo "Automated tests status updated to ${{ needs.update_automated_test_check_status.outputs.status }}"