name: Tag on main push

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Get timestamp
        id: vars
        run: echo "ts=$(date +%y.%m%.d%.H%M%S)" >> $GITHUB_OUTPUT
      - name: Create tag with github-script
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v-${{ steps.vars.outputs.ts }}',
              sha: context.sha
            });
